[package]
authors = ["Yohai Berreby (filsmick) <yohaiberreby@gmail.com>"]
name = "climate"
version = "0.1.0"

[dependencies]
chrono = "0.2.17"
hyper = "0.6.16"
quickcheck = "0.2.24"
serde = "0.6.1"
serde_json = "0.6.0"
